services:
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    app.localization_listener:
        class: AppBundle\EventListener\LocalizationListener
        arguments: ["@l10n_bundle.business.l10n_provider"]
        tags:
            - { name: kernel.event_subscriber }
