services:
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%", @l10n_bundle.business.l10n_provider]
        tags:
            - { name: kernel.event_subscriber }
    app.localization_listener:
        class: AppBundle\EventListener\LocalizationListener
        arguments: ["@l10n_bundle.business.l10n_provider"]
        tags:
            - { name: kernel.event_subscriber }
    app.form.type.group:
        class: AppBundle\Form\GroupType
        tags:
            - { name: form.type, alias: group }
    app.form.type.person:
        class: AppBundle\Form\PersonType
        tags:
            - { name: form.type, alias: person }
